#!/usr/bin/env python3
"""Build AI Agent Incident Tracker: incidents.json -> assets/data.js.

Reads data/incidents.json, computes derived stats (median lag, lagDays per
incident, new-this-week flags), and writes a browser-consumable data.js
exposing them as window.DASH. Also syncs computed totals back into
incidents.json.metadata so the envelope stays honest.
"""
import json, os, sys, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "incidents.json")
OUT = os.path.join(ROOT, "assets", "data.js")

def days(a, b):
    return (datetime.datetime.strptime(b, "%Y-%m-%d")
            - datetime.datetime.strptime(a, "%Y-%m-%d")).days

def main():
    with open(SRC) as f:
        data = json.load(f)
    inc = data["incidents"]

    lag = {i["id"]: days(i["incidentDate"], i["disclosureDate"]) for i in inc}
    lags = sorted(lag.values())
    median = lags[len(lags) // 2] if lags else 0

    today = datetime.date.today()
    week_ago = (today - datetime.timedelta(days=7)).isoformat()
    new_this_week = {i["id"]: i["disclosureDate"] >= week_ago for i in inc}

    data["stats"] = {
        "medianLagDays": median,
        "asOf": today.isoformat(),
        "lagDays": lag,
        "newThisWeek": new_this_week,
    }
    data["metadata"]["totalIncidents"] = len(inc)
    data["metadata"]["disclosureLagMedianDays"] = median

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("/* GENERATED by scripts/build.py — do not edit. */\n")
        f.write("window.DASH = " + json.dumps(data, indent=2) + ";\n")

    with open(SRC, "w") as f:
        json.dump(data, f, indent=2)

    print(f"Wrote {OUT}")
    print(f"  incidents: {len(inc)}")
    print(f"  median disclosure lag: {median} days")
    print(f"  new this week (>= {week_ago}): {sum(new_this_week.values())}")
    print("  metadata synced back to incidents.json")

if __name__ == "__main__":
    sys.exit(main())